server:
  port:

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    driver-class-name: org.postgresql.Driver
    username:
    url:
    password:

  liquibase:
    enabled: true

tmdb:
  token:
  url: https://api.themoviedb.org/3/discover/movie?page=